run-name: Error log testing
on: [pull_request]
jobs:
  Get-new-json:
    runs-on: ubuntu-latest
    steps:
      - name: Warning message
        run: | 
          echo ""::warning title=warning::This is a warning""