name: First test
run-name: API Change testing
on: [push]
jobs:
  Get-new-json:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8
      - name: get openapi json
        run: |
          pip install fastapi
          python json_get.py
      - name: Change filename
        run: mv openapi.json new-json.json
      - name: upload openapi json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: new-json
          path: new-json.json


  Get-old-json:
    runs-on: ubuntu-latest
    steps:
      - name: checkout existing repo
        uses: actions/checkout@v3
        with:
          ref: main
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8
      - name: get openapi json
        run: |
          pip install fastapi
          python json_get.py
      - name: Change file name
        run: mv openapi.json old-json.json
      - name: Upload openapi json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: old-json
          path: old-json.json


  Test-docker-thing:
    runs-on: ubuntu-latest
    needs: [Get-new-json, Get-old-json]
    container:
      image: ahibert/test-api-testing:latest
      volumes:
        old-json:/json_docs
    steps:
      - name: I don't know
        run: python main.py


