name: First test
run-name: Just testing things
on: [push]
jobs:
  First-Attempt:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm working!"

  Python-maybe:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          run: |
            python -m pip install --upgrade pip
            pip install fastapi
        run: |
          from fastapi.openapi.utils import get_openapi
          from main import app
          import json


          with open('openapi.json', 'w') as f:
              json.dump(get_openapi(
                  title=app.title,
                  version=app.version,
                  openapi_version=app.openapi_version,
                  description=app.description,
                  routes=app.routes,
                  openapi_prefix=app.openapi_prefix,
              ), f)