name: First test
run-name: API Change testing
on: [pull_request]
jobs:
  First-Attempt:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm working!"

  Get-new-json:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8
      - name: get openapi json
        run: |
          pip install fastapi
          python json_get.py
      - name: upload openapi json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: new-json
          path: openapi.json


  Get-old-json:
    runs-on: ubuntu-latest
    steps:
      - name: checkout existing repo
        uses: actions/checkout@v3
        with:
          ref: main
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8
      - name: get openapi json
        run: |
          pip install fastapi
          python json_get.py
      - name: upload openapi json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: old-json
          path: openapi.json

  Test-docker-thing:
    needs: Get-new-json, Get-old-json
    runs-on: ubuntu-latest
    container:
      image: ahibert/test-api-test:latest
      volumes:
        - ${pwd}:json_docs
    steps:
      - name: Run docker container??
        run: docker run test-api-test:latest

